apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: outerbridge
  name: outerbridge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: outerbridge
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: outerbridge
    spec:
      containers:
        - args:
            - yarn
            - start
          env:
            - name: ENABLE_TUNNEL
            - name: MONGO_HOST
            - name: PASSPHRASE
            - name: PORT
          image: simplifi:latest
          name: outerbridge
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /root/.outerbridge
              name: outerbridge-claim0
      restartPolicy: Always
      volumes:
        - name: outerbridge-claim0
          persistentVolumeClaim:
            claimName: outerbridge-claim0
status: {}
